# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:

  # Add 'repo' label to any root file changes
  repo:
    - ./*

  # Add 'test' label to any change to *.spec.js files within the source dir
  test:
    - src/**/*.test.jsx

  # Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
  source:
    - any: ['src/**/*', '!src/docs/*']

    runs-on: macos-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
